Repository jenkinsci/levo-plugin, pull requests merged in 2022-09, with the labels that each got.

#4 fix: Setting user and group ids in levo command while running on Linux
  src/main/java/io/jenkins/plugins/levo/helpers/LevoDockerTool.java
Labels: bug

#5 User/Group ID & JUnit reports
  .gitignore
  Vagrantfile
  src/main/java/io/jenkins/plugins/levo/TestPlanBuilder.java
  src/main/java/io/jenkins/plugins/levo/helpers/LevoDockerTool.java
  src/main/resources/io/jenkins/plugins/levo/TestPlanBuilder/config.jelly
  src/main/resources/io/jenkins/plugins/levo/TestPlanBuilder/help-generateJunitReport.html
Labels: bug, feature

#6 Run docker pull before running test plan
  src/main/java/io/jenkins/plugins/levo/helpers/LevoDockerTool.java
Labels: enhancement
